paths_of_data_processing_files = [
    "src/data_processing/__init__.py",
    "src/data_processing/(old) analyze_ids.py",
    "src/data_processing/eda.py",
    "src/data_processing/old_eda.py",
    "src/data_processing/postprocess.py",
    "src/data_processing/README.md",
    "src/data_processing/utils.py"
]

paths_of_other_source_files = [
    "src/cd8_analysis/__init__.py",
    "src/cd8_analysis/cd8_analysis.py",
    "src/cd8_analysis/cd8_groups_analysis.py",
    "src/cd8_analysis/clinical_analysis.py",
    "src/cd8_analysis/README.md",
    
    "src/icb_analysis/__init__.py",
    "src/icb_analysis/[old]advanced_group_analysis.py",
    "src/icb_analysis/[old]icb_analysis.py",
    "src/icb_analysis/group_analysis.py",
    "src/icb_analysis/group_data_loader.py",
    "src/icb_analysis/icb_analysis.py",
    "src/icb_analysis/icb_data_loader.py",
    "src/icb_analysis/icb_main.py",
    "src/icb_analysis/README.md",

    "src/immune_analysis/__init__.py",
    "src/immune_analysis/data_loading.py",
    "src/immune_analysis/immune_analysis.py",
    "src/immune_analysis/microenv.py",
    "src/immune_analysis/OLD_treatment_analysis.py",
    "src/immune_analysis/parse_hgnc_owl.py",
    "src/immune_analysis/readme_microenv.md",
    "src/immune_analysis/README.md",
    "src/immune_analysis/utils.py",
    "src/immune_analysis/wes_integration.py",

    "src/processed_data/icb_data.csv",
    "src/processed_data/processed_clinical_molecular.csv",
    "src/processed_data/processed_clinical.csv",

    "src/utils/__init__.py",
    "src/utils/README.md",
    "src/utils/shared_functions.py",
    "src/__init__.py",

    "README.md",
    "requirements.txt",
    "run_icb_analysis.py",
    "setup.sh",
    "transition.sh"
]

paths_to_data_files = [
    "data/processed/dict_clinical.csv",
    "data/processed/discriminative_genes_Fig4C.csv",
    "data/processed/gene_markers_Fig4AB.csv",
    "data/processed/group_scores.csv",
    "data/processed/hgnc.owl",
    "data/processed/processed_clinical_molecular.csv",
    "data/processed/Subset of Clinical Data.csv",
    "data/processed/two_groups.csv"
]

paths_to_docs = [
    "docs/cd8_analysis_README.md",
    "docs/icb_analysis_README.md",
    "docs/icb_cd8_report.md",
    "docs/readme_cd8_groups.md",
    "docs/readme_cd8.md",
    "docs/readme_microenv.md",
    "docs/readme_treat.md",
    "docs/README.md"
]

paths_to_output_files = [
    "output/immune_analysis/all_focused_results_by_Sex.csv",
    "output/melanoma_analysis/integrated_clinical_wes.csv",
    "output/melanoma_analysis/melanoma_sample_immune_clinical.csv",
    "output/reports/icb_distribution.csv",
    "output/reports/summary_statistics.csv",
    "output/ensembl_to_hugo.csv",
    "output/melanoma_clinical_data.csv",
    "output/melanoma_expression_matrix.csv",
    "output/melanoma_patients_with_sequencing.csv",
    "output/processing_log.txt",
    "output/sample_to_patient_map.csv"
]

paths_to_old_output_files = [
    "output_old/analysis/Adaptive_results.csv",
    "output_old/analysis/Innate_results.csv",
    "output_old/analysis/response_patterns.csv",
    "output_old/analysis/results.md",
    "output_old/analysis/Stromal_results.csv",
    "output_old/analysis/survival_patterns.csv",

    "output_old/cd8_analysis/cd8_groups_analysis/female_group_survival.csv",
    "output_old/cd8_analysis/cd8_groups_analysis/group_sex_differences.csv",
    "output_old/cd8_analysis/cd8_groups_analysis/male_group_survival.csv",
    "output_old/cd8_analysis/clinical_analysis/age_group_counts_by_sex.csv",
    "output_old/cd8_analysis/clinical_analysis/age_group_percentages_by_sex.csv",
    "output_old/cd8_analysis/clinical_analysis/clinical_correlations.csv",
    "output_old/cd8_analysis/clinical_analysis/diagnosis_site_counts_by_sex.csv",
    "output_old/cd8_analysis/clinical_analysis/diagnosis_site_percentages_by_sex.csv",
    "output_old/cd8_analysis/clinical_analysis/primary_recurrent_counts_by_sex.csv",
    "output_old/cd8_analysis/clinical_analysis/primary_recurrent_percentages_by_sex.csv",

    "output_old/cd8_analysis/icb_medication_analysis/CD8_B_by_icb_status.csv",
    "output_old/cd8_analysis/icb_medication_analysis/cd8_by_icb_type.csv",
    "output_old/cd8_analysis/icb_medication_analysis/CD8_G_by_icb_status.csv",
    "output_old/cd8_analysis/icb_medication_analysis/cd8_icb_ttest.csv",
    "output_old/cd8_analysis/icb_medication_analysis/female_ICB_experienced_survival.csv",
    "output_old/cd8_analysis/icb_medication_analysis/female_ICB_naive_survival.csv",
    "output_old/cd8_analysis/icb_medication_analysis/icb_class_by_sex.csv",
    "output_old/cd8_analysis/icb_medication_analysis/icb_findings.txt",
    "output_old/cd8_analysis/icb_medication_analysis/icb_summary.csv",
    "output_old/cd8_analysis/icb_medication_analysis/male_ICB_experienced_survival.csv",
    "output_old/cd8_analysis/icb_medication_analysis/male_ICB_naive_survival.csv",
    "output_old/cd8_analysis/icb_medication_analysis/patient_icb_status_by_sex.csv",
    "output_old/cd8_analysis/icb_medication_analysis/patient_icb_status.csv",
    "output_old/cd8_analysis/icb_medication_analysis/tumor_icb_status_by_sex.csv",
    "output_old/cd8_analysis/zscore_analysis/female_zscore_survival.csv",
    "output_old/cd8_analysis/zscore_analysis/male_zscore_survival.csv",
    "output_old/cd8_analysis/zscore_analysis/raw_expression_sex_differences.csv",
    "output_old/cd8_analysis/zscore_analysis/zscore_sex_differences.csv",
    "output_old/cd8_analysis/female_survival_analysis.csv",
    "output_old/cd8_analysis/male_survival_analysis.csv",
    "output_old/cd8_analysis/signature_correlations.csv",
    "output_old/cd8_analysis/signature_scores.csv",
    "output_old/cd8_analysis/survival_analysis.csv",
    "output_old/data_analysis/molecular/NO_MOLECULAR_DATA.txt",
    "output_old/data_analysis/survival_summary.csv",
    "output_old/icb_analysis/icb_data/icb_patients.csv",
    "output_old/icb_analysis/plots/tme_survival/km_CD8_G_and_Survival__All_Patients_data.csv",
    "output_old/icb_analysis/plots/tme_survival/km_CD8_G_and_Survival__Female_Naive_Patients_data.csv",
    "output_old/icb_analysis/plots/tme_survival/km_CD8_G_and_Survival__Female_Patients_data.csv",
    "output_old/icb_analysis/plots/tme_survival/km_CD8_G_and_Survival__Female_Received_Patients_data.csv",
    "output_old/icb_analysis/plots/tme_survival/km_CD8_G_and_Survival__Male_Naive_Patients_data.csv",
    "output_old/icb_analysis/plots/tme_survival/km_CD8_G_and_Survival__Male_Patients_data.csv",
    "output_old/icb_analysis/plots/tme_survival/km_CD8_G_and_Survival__Male_Received_Patients_data.csv",
    "output_old/icb_analysis/plots/tme_survival/km_CD8_G_and_Survival__Naive_Patients_data.csv",
    "output_old/icb_analysis/plots/tme_survival/km_CD8_G_and_Survival__Received_Patients_data.csv",
    "output_old/icb_analysis/plots/km_ICB_Treatment_and_Overall_Survival_data.csv",
    "output_old/icb_analysis/results/cox_interaction_CD8_G.csv",
    "output_old/icb_analysis/results/icb_targets.csv",
    "output_old/melanoma_analysis/logs/eda_20250414_164150.log",
    "output_old/melanoma_analysis/logs/eda_20250414_164207.log",
    "output_old/melanoma_analysis/logs/eda_20250414_164425.log",
    "output_old/melanoma_analysis/logs/eda_20250414_170258.log",
    "output_old/melanoma_analysis/logs/eda_20250415_030838.log",
    "output_old/melanoma_analysis/logs/eda_20250415_031226.log",
    "output_old/melanoma_analysis/logs/eda_20250415_031340.log",
    "output_old/melanoma_analysis/logs/eda_20250415_031658.log",
    "output_old/melanoma_analysis/logs/eda_20250415_031953.log",
    "output_old/melanoma_analysis/molecular/NO_MOLECULAR_DATA.txt",
    "output_old/melanoma_analysis/melanoma_patients.csv",
    "output_old/melanoma_analysis/survival_summary.csv",
    "output_old/melanoma_analysisclear/logs/eda_20250415_031220.log",
    "output_old/plots/eda/cox_model_summary.txt",
    "output_old/processed_data/melanoma_clinical_processed.csv",
    "output_old/processed_data/processed_clinical.csv",
    "output_old/sex_analysis/sex_differences_immune.csv",
    "output_old/sex_analysis/sex_differences.csv",
    "output_old/sex_analysis/tcell_sex_differences.csv",
    "output_old/cell_scores.csv",
    "output_old/merged_immune_clinical.csv"
]
